### PR TITLE
Use ES6 modules

### PR DESCRIPTION
**Pull request by ebrelsford**
Use ES6 module syntax (`export`) rather than setting `module.exports`, which appears to keep Parcel from exporting the function as expected.

### CODE REVIEW

**Review by aparlato — COMMENTED** [review]
This works for the module itself, but like we discussed, it breaks the standalone viewer because of the `export`.

Should we hold on merging this until we [remove the viewer from this repo](https://github.com/stamen/mapbox-gl-style-diff/issues/12) so it becomes a non-issue? Looks like there's already an [open draft PR](https://github.com/stamen/mapbox-gl-style-diff/pull/15/files) for that.

**Review by aparlato — APPROVED** [review]
@ebrelsford sure that works for me. I'm running into a bit of a CORS issue despite my CORS extension on Chrome due to referencing a local ES6 module I think. I think I could run Chrome without web security instead of using the extension, but for ease of use in case others run into the same issue, what do you think of adding `http-server` or some similar simple library to serve the HTML page to get around this? 

Let me know if there's a different better way I should be handling CORS here! Approving to unblock since this is at your discretion.

**Comment by ebrelsford** [comment]
> what do you think of adding http-server or some similar simple library to serve the HTML page to get around this?

Weird I wasn't seeing that! I'm serving the page with Python (`python3 -m http.server`) without any issues.

Let's avoid working on this more if we can because I think we can move over to the [diff-viewer](https://github.com/stamen/mapbox-gl-style-diff-viewer) soon.

**Comment by aparlato** [comment]
> I'm serving the page with Python (python3 -m http.server) without any issues

That makes sense! I was dropping the HTML file straight into the browser. Loading off any http server solves this CORS issue.

> Let's avoid working on this more if we can because I think we can move over to the [diff-viewer](https://github.com/stamen/mapbox-gl-style-diff-viewer)[](https://github.com/ebrelsford) soon.

👍

**Pull request merged**
